# Generated by Django 2.2.19 on 2021-02-23 13:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_squashed_0005_CreateTeamModel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=jsonfield.fields.JSONField(blank=True, db_column='raw_answer'),
        ),
    ]
